version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/web-service:latest --replicas 2 --network backend"
    environment:
      PORT: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
  proxy:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./src/reverse-proxy/Dockerfile
    environment:
      PORT: 8080
      CONFIG_FILE: $CONFIG_FILE
    networks:
      - backend
  user:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/user-service:latest --replicas 2 --network backend"
    environment:
      PORT: 8080
      JWT_PRIVATE_KEY: $JWT_PRIVATE_KEY
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
  book:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/book-service:latest --replicas 2 --network backend"
    environment:
      AUTH_URL_ENDPOINT: http://user:8080/validate_token
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
  transaction:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/transaction-service:latest --replicas 2 --network backend"
    environment:
      AUTH_URL_ENDPOINT: http://user:8080/validate_token
      BOOK_SERVICE_ENDPOINT: http://book:8080/verify_chapter_id
      USER_SERVICE_ENDPOINT: http://user:8080/move_user_amount
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
    name: backend
