version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/web-service:latest --replicas 2 --network backend"
    environment:
      PORT: 8080
      HEALTH_TIMEOUT: 200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
  proxy:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./src/reverse-proxy/Dockerfile
    environment:
      PORT: 8080
      HEALTH_TIMEOUT: 200
      CONFIG_FILE: $CONFIG_FILE
    networks:
      - backend
  user:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/user-service:latest --replicas 2 --network backend"
    environment:
      AUTH_IS_ACTIVE: $AUTH_IS_ACTIVE
      GRPC_COMMUNICATION: false
      PORT: 8080
      HEALTH_TIMEOUT: 200
      JWT_ACCESS_PRIVATE_KEY: $JWT_ACCESS_PRIVATE_KEY
      JWT_ACCESS_PUBLIC_KEY: $JWT_ACCESS_PUBLIC_KEY
      JWT_REFRESH_PRIVATE_KEY: $JWT_REFRESH_PRIVATE_KEY
      JWT_REFRESH_PUBLIC_KEY: $JWT_REFRESH_PUBLIC_KEY
      JWT_ACCESS_TOKEN_EXPIRATION: $JWT_ACCESS_TOKEN_EXPIRATION
      JWT_REFRESH_TOKEN_EXPIRATION: $JWT_REFRESH_TOKEN_EXPIRATION
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
      test-data:
        condition: service_healthy
  book:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/book-service:latest --replicas 2 --network backend"
    environment:
      AUTH_IS_ACTIVE: $AUTH_IS_ACTIVE
      GRPC_COMMUNICATION: false
      AUTH_SERVICE_ENDPOINT: http://user:8080/validate-token
      TRANSACTION_SERVICE_ENDPOINT: http://transaction:8080/check-chapter-bought
      PORT: 8080
      HEALTH_TIMEOUT: 200
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
      test-data:
        condition: service_healthy
  transaction:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/transaction-service:latest --replicas 2 --network backend"
    environment:
      AUTH_IS_ACTIVE: $AUTH_IS_ACTIVE
      GRPC_COMMUNICATION: false
      AUTH_SERVICE_ENDPOINT: http://user:8080/validate-token
      BOOK_SERVICE_ENDPOINT: http://book:8080/valdiate-chapter-id
      USER_SERVICE_ENDPOINT: http://user:8080/move-user-amount
      PORT: 8080
      HEALTH_TIMEOUT: 200
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
      test-data:
        condition: service_healthy
  test-data:
    build:
      context: .
      dockerfile: ./src/load-balancer/Dockerfile
    command: "--image akatranlp/test-data-service:latest --replicas 2 --network backend"
    environment:
      RESET_ON_INIT: true
      TEST_DATA_USER_PASSWORD: $TEST_DATA_USER_PASSWORD
      TEST_DATA_FILE: $TEST_DATA_FILE
      PORT: 8080
      HEALTH_TIMEOUT: 200
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    healthcheck:
      test: curl -q --fail http://localhost:8080/health
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 5

    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
    name: backend
