version: "3.9"

services:
  proxy:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./src/reverse-proxy/Dockerfile
    # restart: unless-stopped
    environment:
      PORT: 8080
      CONFIG_FILE: $CONFIG_FILE
    links:
      - web
      - user
      - book
      - transaction
  web:
    build:
      context: .
      dockerfile: ./src/web-service/Dockerfile
    # restart: unless-stopped
  user:
    build:
      context: .
      dockerfile: ./src/user-service/Dockerfile
    environment:
      PORT: 8080
      JWT_PRIVATE_KEY: $JWT_PRIVATE_KEY
      JWT_PUBLIC_KEY: $JWT_PUBLIC_KEY
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    # restart: unless-stopped
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  book:
    build:
      context: .
      dockerfile: ./src/book-service/Dockerfile
    environment:
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    # restart: unless-stopped
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      user:
        condition: service_started
  transaction:
    build:
      context: .
      dockerfile: ./src/transaction-service/Dockerfile
    environment:
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    # restart: unless-stopped
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      user:
        condition: service_started
      book:
        condition: service_started
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
