version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./src/web-service/Dockerfile
    environment:
      PORT: 8080
      TZ: Europe/Berlin
    networks:
      - backend
  proxy:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./src/reverse-proxy/Dockerfile
    environment:
      PORT: 8080
      CONFIG_FILE_PATH: /config.yaml
      TZ: Europe/Berlin
    volumes:
      - ./src/reverse-proxy/config.yaml:/config.yaml
    networks:
      - backend
  user:
    build:
      context: .
      dockerfile: ./src/user-service/Dockerfile
    environment:
      AUTH_IS_ACTIVE: true
      PORT: 8080
      GRPC_PORT: 8081
      JWT_PRIVATE_KEY_PATH: /certs/key.pem
      JWT_PUBLIC_KEY_PATH: /certs/public.pem
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    volumes:
      - type: bind
        source: ./src/user-service/certs
        target: /certs
        read_only: true
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
  book:
    build:
      context: .
      dockerfile: ./src/book-service/Dockerfile
    environment:
      AUTH_IS_ACTIVE: true
      AUTH_SERVICE_ENDPOINT: http://user:8081
      TRANSACTION_SERVICE_ENDPOINT: http://transaction:8081
      PORT: 8080
      GRPC_PORT: 8081
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
  transaction:
    build:
      context: .
      dockerfile: ./src/transaction-service/Dockerfile
    environment:
      AUTH_IS_ACTIVE: true
      AUTH_SERVICE_ENDPOINT: http://user:8081
      BOOK_SERVICE_ENDPOINT: http://book:8081
      USER_SERVICE_ENDPOINT: http://user:8081
      PORT: 8080
      GRPC_PORT: 8081
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
  test-data:
    build:
      context: .
      dockerfile: ./src/test-data-service/Dockerfile
    environment:
      RESET_ON_INIT: true
      TEST_DATA_USER_PASSWORD: $TEST_DATA_USER_PASSWORD
      TEST_DATA_FILE_PATH: /init.sql
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    volumes:
      - type: bind
        source: ./src/test-data-service/init.sql
        target: /init.sql
        read_only: true
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      TZ: Europe/Berlin
    networks:
      - backend
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
    name: backend
