version: "3.9"

services:
  proxy-kubernetes:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./src/reverse-proxy/Dockerfile
    environment:
      PORT: 8080
      CONFIG_FILE: $CONFIG_FILE_HELP
    networks:
      - minikube

networks:
  minikube:
    name: minikube
    external: true
