// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protobuf/transaction_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckChapterBoughtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ChapterId uint64 `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	BookId    uint64 `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *CheckChapterBoughtRequest) Reset() {
	*x = CheckChapterBoughtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_transaction_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckChapterBoughtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChapterBoughtRequest) ProtoMessage() {}

func (x *CheckChapterBoughtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_transaction_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChapterBoughtRequest.ProtoReflect.Descriptor instead.
func (*CheckChapterBoughtRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckChapterBoughtRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckChapterBoughtRequest) GetChapterId() uint64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *CheckChapterBoughtRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type CheckChapterBoughtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *CheckChapterBoughtResponse) Reset() {
	*x = CheckChapterBoughtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_transaction_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckChapterBoughtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckChapterBoughtResponse) ProtoMessage() {}

func (x *CheckChapterBoughtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_transaction_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckChapterBoughtResponse.ProtoReflect.Descriptor instead.
func (*CheckChapterBoughtResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckChapterBoughtResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protobuf_transaction_service_proto protoreflect.FileDescriptor

var file_protobuf_transaction_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x69, 0x0a, 0x19, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x67, 0x68, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x6d, 0x0a,
	0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x42, 0x6f, 0x75, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x42, 0x6f, 0x75,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x42, 0x6f,
	0x75, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_transaction_service_proto_rawDescOnce sync.Once
	file_protobuf_transaction_service_proto_rawDescData = file_protobuf_transaction_service_proto_rawDesc
)

func file_protobuf_transaction_service_proto_rawDescGZIP() []byte {
	file_protobuf_transaction_service_proto_rawDescOnce.Do(func() {
		file_protobuf_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_transaction_service_proto_rawDescData)
	})
	return file_protobuf_transaction_service_proto_rawDescData
}

var file_protobuf_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_transaction_service_proto_goTypes = []interface{}{
	(*CheckChapterBoughtRequest)(nil),  // 0: main.CheckChapterBoughtRequest
	(*CheckChapterBoughtResponse)(nil), // 1: main.CheckChapterBoughtResponse
}
var file_protobuf_transaction_service_proto_depIdxs = []int32{
	0, // 0: main.TransactionService.CheckChapterBought:input_type -> main.CheckChapterBoughtRequest
	1, // 1: main.TransactionService.CheckChapterBought:output_type -> main.CheckChapterBoughtResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_transaction_service_proto_init() }
func file_protobuf_transaction_service_proto_init() {
	if File_protobuf_transaction_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_transaction_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckChapterBoughtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_transaction_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckChapterBoughtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_transaction_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_transaction_service_proto_goTypes,
		DependencyIndexes: file_protobuf_transaction_service_proto_depIdxs,
		MessageInfos:      file_protobuf_transaction_service_proto_msgTypes,
	}.Build()
	File_protobuf_transaction_service_proto = out.File
	file_protobuf_transaction_service_proto_rawDesc = nil
	file_protobuf_transaction_service_proto_goTypes = nil
	file_protobuf_transaction_service_proto_depIdxs = nil
}
