apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
      annotations:
        author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
    spec:
      containers:
        - name: web-service
          image: akatranlp/web-service:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  selector:
    app: web-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
