apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
      annotations:
        author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
    spec:
      containers:
        - name: book-service
          image: akatranlp/book-service:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_IS_ACTIVE
              value: "true"
            - name: TRANSACTION_SERVICE_ENDPOINT
              value: http://transaction-service:8081
            - name: AUTH_SERVICE_ENDPOINT
              value: http://user-service:8081
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "8081"
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 8081
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  selector:
    app: book-service
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 8081
      targetPort: grpc
