apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
    spec:
      containers:
        - name: user-service
          image: akatranlp/user-service:latest
          imagePullPolicy: Always
          env:
            - name: AUTH_IS_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: AUTH_IS_ACTIVE
            - name: GRPC_COMMUNICATION
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: GRPC_COMMUNICATION
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "8081"
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: JWT_PRIVATE_KEY_PATH
              value: /certs/key.pem
            - name: JWT_PUBLIC_KEY_PATH
              value: /certs/public.pem
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 8081
          volumeMounts:
            - name: user-jwt
              mountPath: /certs
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
      volumes:
        - name: user-jwt
          secret:
            secretName: user-jwt-secret
            optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 8081
      targetPort: grpc
