apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: hsfl-fape2866
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
    spec:
      containers:
        - name: user-service
          image: akatranlp/user-service:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: JWT_PRIVATE_KEY_PATH
              value: /certs/id_rsa
            - name: JWT_PUBLIC_KEY_PATH
              value: /certs/id_rsa.pub
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: user-jwt
              mountPath: /certs
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
      volumes:
        - name: user-jwt
          secret:
            secretName: user-jwt-secret
            optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: hsfl-fape2866
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 8080
      targetPort: http
