// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protobuf/book_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateChapterIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ChapterId uint64 `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	BookId    uint64 `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
}

func (x *ValidateChapterIdRequest) Reset() {
	*x = ValidateChapterIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_book_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateChapterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateChapterIdRequest) ProtoMessage() {}

func (x *ValidateChapterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_book_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateChapterIdRequest.ProtoReflect.Descriptor instead.
func (*ValidateChapterIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_book_service_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateChapterIdRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateChapterIdRequest) GetChapterId() uint64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ValidateChapterIdRequest) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

type ValidateChapterIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterId       uint64 `protobuf:"varint,1,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	BookId          uint64 `protobuf:"varint,2,opt,name=bookId,proto3" json:"bookId,omitempty"`
	ReceivingUserId uint64 `protobuf:"varint,3,opt,name=receivingUserId,proto3" json:"receivingUserId,omitempty"`
	Amount          uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ValidateChapterIdResponse) Reset() {
	*x = ValidateChapterIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_book_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateChapterIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateChapterIdResponse) ProtoMessage() {}

func (x *ValidateChapterIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_book_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateChapterIdResponse.ProtoReflect.Descriptor instead.
func (*ValidateChapterIdResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_book_service_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateChapterIdResponse) GetChapterId() uint64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ValidateChapterIdResponse) GetBookId() uint64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *ValidateChapterIdResponse) GetReceivingUserId() uint64 {
	if x != nil {
		return x.ReceivingUserId
	}
	return 0
}

func (x *ValidateChapterIdResponse) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_protobuf_book_service_proto protoreflect.FileDescriptor

var file_protobuf_book_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d,
	0x61, 0x69, 0x6e, 0x22, 0x68, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x22, 0x93, 0x01,
	0x0a, 0x19, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6f, 0x6f,
	0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x32, 0x63, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_book_service_proto_rawDescOnce sync.Once
	file_protobuf_book_service_proto_rawDescData = file_protobuf_book_service_proto_rawDesc
)

func file_protobuf_book_service_proto_rawDescGZIP() []byte {
	file_protobuf_book_service_proto_rawDescOnce.Do(func() {
		file_protobuf_book_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_book_service_proto_rawDescData)
	})
	return file_protobuf_book_service_proto_rawDescData
}

var file_protobuf_book_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_book_service_proto_goTypes = []interface{}{
	(*ValidateChapterIdRequest)(nil),  // 0: main.ValidateChapterIdRequest
	(*ValidateChapterIdResponse)(nil), // 1: main.ValidateChapterIdResponse
}
var file_protobuf_book_service_proto_depIdxs = []int32{
	0, // 0: main.BookService.ValidateChapterId:input_type -> main.ValidateChapterIdRequest
	1, // 1: main.BookService.ValidateChapterId:output_type -> main.ValidateChapterIdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_book_service_proto_init() }
func file_protobuf_book_service_proto_init() {
	if File_protobuf_book_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_book_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateChapterIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_book_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateChapterIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_book_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_book_service_proto_goTypes,
		DependencyIndexes: file_protobuf_book_service_proto_depIdxs,
		MessageInfos:      file_protobuf_book_service_proto_msgTypes,
	}.Build()
	File_protobuf_book_service_proto = out.File
	file_protobuf_book_service_proto_rawDesc = nil
	file_protobuf_book_service_proto_goTypes = nil
	file_protobuf_book_service_proto_depIdxs = nil
}
