{
 "title": "Kubernetes Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utils [%]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (avg by (instance) (rate(node_cpu_seconds_total{mode= \"idle\", kubernetes_name=\"\" }[1m])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{kubernetes_name=\"\"}[1m]) + avg_over_time(node_memory_Cached_bytes{kubernetes_name=\"\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{kubernetes_name=\"\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{kubernetes_name=\"\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total[1m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(rate(container_network_receive_bytes_total[1m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}