// Code generated by MockGen. DO NOT EDIT.
// Source: auth/config.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=_mocks/config.go -source=auth/config.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// ReadPrivateKey mocks base method.
func (m *MockConfig) ReadPrivateKey() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPrivateKey")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPrivateKey indicates an expected call of ReadPrivateKey.
func (mr *MockConfigMockRecorder) ReadPrivateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPrivateKey", reflect.TypeOf((*MockConfig)(nil).ReadPrivateKey))
}

// ReadPublicKey mocks base method.
func (m *MockConfig) ReadPublicKey() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPublicKey")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPublicKey indicates an expected call of ReadPublicKey.
func (mr *MockConfigMockRecorder) ReadPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPublicKey", reflect.TypeOf((*MockConfig)(nil).ReadPublicKey))
}
