apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: hsfl-fape2866
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
      annotations:
        author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
    spec:
      containers:
        - name: transaction-service
          image: akatranlp/transaction-service:latest
          env:
            - name: AUTH_URL_ENDPOINT
              value: http://user:8080/validate_token
            - name: BOOK_SERVICE_ENDPOINT
              value: http://book:8080/verify_chapter_id
            - name: USER_SERVICE_ENDPOINT
              value: http://user:8080/move_user_amount
            - name: PORT
              value: "8080"
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: hsfl-fape2866
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8080
      targetPort: http
