// Code generated by MockGen. DO NOT EDIT.
// Source: controller/controller.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=_mocks/controller.go -source=controller/controller.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// ResetDatabase mocks base method.
func (m *MockController) ResetDatabase(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetDatabase", arg0, arg1)
}

// ResetDatabase indicates an expected call of ResetDatabase.
func (mr *MockControllerMockRecorder) ResetDatabase(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetDatabase", reflect.TypeOf((*MockController)(nil).ResetDatabase), arg0, arg1)
}
