# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lib Test

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "!lib/docs/**"
      - "!lib/README.md"
    branches: ["main"]
  pull_request:
    paths:
      - "lib/**"
      - "!lib/docs/**"
      - "!lib/README.md"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"

      - name: Install dependencies
        working-directory: ./lib
        run: go mod tidy

      - name: Test
        working-directory: ./lib
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
