# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Reverse Proxy Test

on:
  workflow_dispatch:
  push:
    paths: 
      - 'src/reverse-proxy/**'
      - '!src/reverse-proxy/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/reverse-proxy/**'
      - '!src/reverse-proxy/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Install dependencies
      working-directory: ./src/reverse-proxy
      run: go get .

    - name: Build
      working-directory: ./src/reverse-proxy
      run: go build -v ./...

    - name: Test
      working-directory: ./src/reverse-proxy
      run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
