# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: User Service Test

on:
  workflow_dispatch:
  push:
    paths: 
      - 'src/user-service/**'
      - '!src/user-service/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/user-service/**'
      - '!src/user-service/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Install dependencies
      working-directory: ./src/user-service
      run: go get .

    - name: Build
      working-directory: ./src/user-service
      run: go build -v ./...

    - name: Test
      working-directory: ./src/user-service
      run: go test -v ./...
