# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Web Service Test

on:
  workflow_dispatch:
  push:
    paths: 
      - 'src/web-service/**'
      - '!src/web-service/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/web-service/**'
      - '!src/web-service/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install deps
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Lint
      run: pnpm lint
