# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Web Service Test

on:
  workflow_dispatch:
  push:
    paths: 
      - 'src/web-service/**'
      - '!src/web-service/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/web-service/**'
      - '!src/web-service/docs/**'
      - 'lib/**'
      - '!lib/docs/**'
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/web-service
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
        package_json_file: ./src/web-service/package.json
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install deps
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Lint
      run: pnpm lint
