apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-data-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-data-service
  template:
    metadata:
      labels:
        app: test-data-service
      annotations:
        author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
    spec:
      containers:
        - name: test-data-service
          image: akatranlp/test-data-service:latest
          imagePullPolicy: Always
          env:
            - name: RESET_ON_INIT
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: RESET_ON_INIT
            - name: TEST_DATA_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-data-secret
                  key: TEST_DATA_USER_PASSWORD
            - name: TEST_DATA_FILE_PATH
              value: /sql/init.sql
            - name: PORT
              value: "8080"
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: test-data-sql
              mountPath: /sql
              readOnly: true
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
      volumes:
        - name: test-data-sql
          configMap:
            name: test-data-sql-config
---
apiVersion: v1
kind: Service
metadata:
  name: test-data-service
  namespace: hsfl-verse-vault
  annotations:
    author: Fabian Petersen <fabian@nf-petersen.de | fabian.petersen@stud.hs-flensburg.de>
spec:
  selector:
    app: test-data-service
  ports:
    - name: http
      port: 8080
      targetPort: http
